### ISSUE TITLE
error 2406 skill id invalid. 

### ISSUE THREAD

**Issue by wemo666** [jurgenheine/com.tuya.cloud#104]
error 2406 skill id invalid.

**Comment by wemo666** [comment]
I read the instructions and follow to the T and cannot get app to work. 2406 error. I created a second project and got a different access id and secret and central europe data center. coutry code of 61 in homey tuya app. same error 2406. What do I need to do to get his app working again? Thanks.

**Comment by JohPePe** [comment]
I’ve got the exact same problem! How to solve it?

**Comment by wemo666** [comment]
Did you scan the barcode?

**Comment by JohPePe** [comment]
If you are asking me, yes I did scan the qr-code.

**Comment by JohPePe** [comment]
Tried to scan the code again, just to be sure.
Got an error message telling me my Tuya smart app is already linked to two projects.
But no linked devices are shown, not for the old project and not for the new.
I’m stumped! 🤔
![1D007058-61E7-42D2-AA71-4EF351A4CF8F](https://user-images.githubusercontent.com/25219053/187105440-8ec79cdf-3853-424e-890b-5da1ab1214c1.jpeg)
![0DD7738A-F553-47A3-83AD-EF446819A6FA](https://user-images.githubusercontent.com/25219053/187105451-a15589e9-08b3-4be9-a50e-1491b724ff54.jpeg)

**Comment by wemo666** [comment]
I am not sure. But I did have to restart the Tuya Homey app for it work.

**Comment by jurgenheine** [comment]
Please continue this conversation on the forum. There are users who can help. I don't have all the answeres. I am an community developer and not working for Tuya or Athom. The errors are coming directly from Tuya platform. I have added a faq and possible error codes. But those are also come from Tuya github site. In Forum other users can help with problems on Tuya platform themself because they experience the same problem and found a solution. 

Issues here are for bugs  in the app and device requests and not for configuration questions and help.
