### ISSUE TITLE
LED Bulb GU10 full color not working correct

### ISSUE THREAD

**Issue by ludvigaldrin** [jurgenheine/com.tuya.cloud#11]
Hi!
I have a Led Bulb Gu10 with full colour. Have connected it to Tuya App (Also Smartlife app for testing) and hooked up my Homey to Tuya Cloud. I can find the bulb and it shows up. However it shows up as a normal dimmable lamp. So it has on/off and dim. The on/off works but dim is not working. And of course the big thing Im missing is the color part. I guess this is whats sometimes called HUE? Is it just missing configuration to match that bulb or what could be wrong? I see in the code that there is capability called light_hue. And you talk about it in the config too.

Please let me know if I can test anything for you.

This is the bulb:
https://nedis.com/en-us/product/smart-living/smart-home/lighting/550678394/wifi-smart-led-bulb-full-colour-and-warm-white-gu10

**Comment by jurgenheine** [comment]
There are now 2 light types. The old light type is fully supported by the Tuya cloud API, which this app uses. The other newer type is partialy supported by the API, so also partialy supported by this app. The newer type was first only used by led-strips. But I see more and more that other light types starting to use this type. Because the API does not support fully this new light type, this app can't support it fully too.

**Comment by jurgenheine** [comment]
See also [https://github.com/jurgenheine/com.tuya.cloud/issues/9#issuecomment-595994540]

**Comment by jurgenheine** [comment]
Should work now with new API
