### ISSUE TITLE
Devices (temporarily unavailable

### ISSUE THREAD

**Issue by poeligoal** [jurgenheine/com.tuya.cloud#34]
Hi,
New on homey so maybe i am doing someyhing wrong. I installed the Tuya app and did the setup. I was able to add the devices that i have set up in the Smart Life app. However, in the homey app they all have a error message (!) stating that it is unavailable?
In the smartlife app it all works perfectly? So, what should i do?

thanks!

**Comment by poeligoal** [comment]
Devices are on/off switch and plugs

**Comment by guff-se** [comment]
I'm having the same issue. Adding works fine, but the devices are (temporary) unavailable.
Using two different Tuya switches. Works fine when controlling from Tuya app.

**Comment by jurgenheine** [comment]
Unfortunality it's because Tuya allows only once in the 10 minutes to query the status. After adding the device, Homey wants to know the status, so a query is performed to Tuya Cloud API, which response with an error that only once in 10 minutes a call is allowed. This error results in the (temporary) unavailable. If you wait 10 minutes it should work.

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details
