### ISSUE TITLE
The complete app crached. Multipele conectors are complete down

### ISSUE THREAD

**Issue by marcel-1984** [jurgenheine/com.tuya.cloud#43]

**Comment by Jeffreyvl1987** [comment]
hey marcel,
 same problem here are you still having trouble?

**Comment by marcel-1984** [comment]
Hey jeffrey, 

yes unfortunately it is not solved yet

**Comment by Jeffreyvl1987** [comment]
Let's hope this gets resolved soon. As a novice user of homey, that is very disappointing. I hope this doesn't happen regularly.

**Comment by marcel-1984** [comment]
that is definitely true. that's why I want more and more zigbee and less wifi or depend on a cloud

**Comment by Jeffreyvl1987** [comment]
I fully understand unfortunately I had already bought almost everything from lighting for the house. the tuya app seemed to me to be the ideal solution in combination with homey. If this happens regularly, it might be best to switch, just a shame about the extra costs

**Comment by Aibola** [comment]
Please Marcel,

This app crashed completely and is doing nothing anymore. All flows are broken cause the devices are not recognized anymore. This is a huge problem. As an end-user I think It would be a logical move to retract such a unstable app from the Homey repository. I've spoken with friends who also use Tuya clouded  with wifi devices and they are having the same issues.

Not very pleasant when the switches are installed for instance in the children's bedroom and there panic button won't work at night. It's strange because the Tuya app works prefect.

Is there another way to connect to the wifi devices?

**Comment by marcel-1984** [comment]
I also do have child related sensors. That's really not nice with a malfunction. now everything seems to be working fine again

**Comment by Aibola** [comment]
Just now I reconnected my Google home hub and all devices showed up again. At least I have my voice commands back.
It is still weird you don't get a confirmation that the app from Homey actually makes a connection it only says Reconnected Gateway which I verymuch doubt. I still don't see devices in Homey.

**Comment by jurgenheine** [comment]
See also #41

**Comment by jurgenheine** [comment]
[Community forum](https://community.athom.com/t/app-tuya-cloud/21313/370)

**Comment by Aibola** [comment]
SO still not working even after factory reset of Homey and update to 0.0.15.
I don't know why on the bottom is say Hue color lamp in the interface at the port of Tuya Clous settings.
Also password doesn't matter you put it in and every time  it says Reconnected to gateway. Even with an incorrect password.

**Comment by jurgenheine** [comment]
There is now an other API used in the test version. You can try now if this solves your problem. See forum for details
