### ISSUE TITLE
No new devices

### ISSUE THREAD

**Issue by dxfoxd** [jurgenheine/com.tuya.cloud#52]
Not sure what I'm doing wrong. Configured the Tuya IoT Cloud project, Homey settings, connected OK. Have 6 devices in API, socket, 3 LED bulbs and 2 blinds, but nothing is showing up. Only message "No new devices found". 
Edit: Even the function reconnect replies with "Reconnected to gateway", even if you deliberately type a wrong password. So authentication protocol has flaws as well. Well, done with this app. I do my integration from HA myself.

**Comment by jurgenheine** [comment]
Did you use the right credentials and not the linked google account credentials.

**Comment by dxfoxd** [comment]
No, exactly as described in the setup steps 2 and 3 (Tuya App credentials). These credentials are not linked to Google.

**Comment by jurgenheine** [comment]
The values you enter in settings screen are passed directly to the Tuya API, so there is something wrong. But I just realize you are using credentials of Tuya IOT project instead of the credentials for the android app. The IOT is needed for the new API connection just like the version 2 off the HA integration. But this is released yesterday. See forum for details how to connect.

**Comment by dxfoxd** [comment]
OK I will check soon, because Device > Tuya <app> HA <app> Homey is not favorable to maintain as well...

**Comment by jurgenheine** [comment]
The new version in test is now using the same API as the Tuya HA version 2.
