### ISSUE TITLE
New device asks for app setup

### ISSUE THREAD

**Issue by RNuberg** [jurgenheine/com.tuya.cloud#80]
Since shortly if I try to add a new device (or reinstall the app) ik asks to configure the app (requiring id and key)

**Comment by grritvrij** [comment]
I have the same problemen, i hoop you can help.

**Comment by frodeheg** [comment]
Yes, what is "Official API access ID" and "Official API Access Secret"?

**Comment by DennisMeeki** [comment]
Same here need to enter api acces id. Where can I find it? Tried it on the tuya developer site but no succes. Please help

**Comment by grritvrij** [comment]
access id  uenvge5abfppyix84hzgaccess secret
 c9a2556d287442c98f7969cee56d7fb4

Op zo 20 mrt. 2022 01:45 schreef frodeheg ***@***.***>:

**Comment by jurgenheine** [comment]
Maybe there is a read.me for a reason and shown when get on this github, it's all there.
Also there is [forum ](https://community.homey.app/t/app-pro-tuya-cloud/21313) topic and several howto's
@grritvrij, i have hide your post because of sensitive data you posted. Never post login data and secrets!!

**Comment by grritvrij** [comment]
good day i had a moment yesterday when some devices were working but wanted to add more and it says the app needs to be set up. Restarted the app and nothing works now. can anybody help me. Gr Gerrit
